"use strict";const assert=require("node:assert/strict"),test=require("node:test"),L=require("../src/core.js");
function audit(title,score,numericValue,numericUnit="millisecond",extra={}){return Object.assign({title,description:title+" description",score,scoreDisplayMode:"numeric",numericValue,numericUnit,displayValue:L.formatValue(numericValue,numericUnit)},extra)}
function fixture(){return{lighthouseVersion:"13.0.0",fetchTime:"2026-08-17T00:00:00Z",requestedUrl:"https://user:pass@example.com/?token=secret",finalDisplayedUrl:"https://example.com/app?token=secret#main",configSettings:{formFactor:"mobile"},runWarnings:["CPU throttling unavailable"],audits:{"first-contentful-paint":audit("First Contentful Paint",.85,1900),"largest-contentful-paint":audit("Largest Contentful Paint",.6,3100),"total-blocking-time":audit("Total Blocking Time",.9,180),"cumulative-layout-shift":audit("Cumulative Layout Shift",.95,.08,"unitless"),"speed-index":audit("Speed Index",.7,3700),"total-byte-weight":audit("Total byte weight",.5,2*1024*1024,"byte"),"unused-javascript":audit("Reduce unused JavaScript",.4,400,"millisecond",{details:{type:"opportunity",overallSavingsMs:650,overallSavingsBytes:120000,items:[{url:"https://example.com/app.js"}]}}),"meta-description":{title:"Document has a meta description",description:"SEO",score:1,scoreDisplayMode:"binary"},"manual-audit":{title:"Manual check",description:"Review",score:null,scoreDisplayMode:"manual"}},categories:{performance:{title:"Performance",score:.72,auditRefs:[{id:"first-contentful-paint",weight:10},{id:"largest-contentful-paint",weight:25},{id:"missing",weight:0}]},accessibility:{title:"Accessibility",score:.96,auditRefs:[]},seo:{title:"SEO",score:.91,auditRefs:[{id:"meta-description",weight:1}]}},fullPageScreenshot:{screenshot:{data:"private"}},timing:{total:1000}}}
test("parses object and BOM JSON without mutation",()=>{const x=fixture(),before=JSON.stringify(x);assert.equal(L.parseLhr(x),x);assert.equal(L.parseLhr("\uFEFF"+before).lighthouseVersion,"13.0.0");L.analyzeLhr(x);assert.equal(JSON.stringify(x),before)});
test("rejects empty malformed arrays and missing report sections",()=>{assert.throws(()=>L.parseLhr(""),/empty/);assert.throws(()=>L.parseLhr("{bad}"),/Invalid/);assert.throws(()=>L.parseLhr([]),/root/);assert.throws(()=>L.parseLhr({audits:{}}),/audits and categories/)});
test("normalizes audit scoring states",()=>{const a=L.analyzeLhr(fixture()).audits;assert.equal(a.find(x=>x.id==="unused-javascript").state,"error");assert.equal(a.find(x=>x.id==="largest-contentful-paint").state,"warning");assert.equal(a.find(x=>x.id==="meta-description").state,"pass");assert.equal(a.find(x=>x.id==="manual-audit").state,"info")});
test("normalizes categories and missing audit references",()=>{const r=L.analyzeLhr(fixture());assert.equal(r.categories[0].scorePercent,72);assert.equal(r.categories[0].auditRefs[0].audit.id,"first-contentful-paint");assert.ok(r.issues.some(x=>x.code==="audit-ref"))});
test("extracts metrics with labels and budgets",()=>{const m=L.analyzeLhr(fixture()).metrics;assert.equal(m.find(x=>x.id==="largest-contentful-paint").label,"LCP");assert.equal(m.find(x=>x.id==="cumulative-layout-shift").defaultBudget,.1)});
test("extracts and sorts opportunities",()=>{const r=L.analyzeLhr(fixture());assert.equal(r.opportunities[0].id,"unused-javascript");assert.equal(r.summary.totalSavingsMs,650);assert.equal(r.summary.totalSavingsBytes,120000)});
test("summarizes report metadata and counts",()=>{const r=L.analyzeLhr(fixture());assert.equal(r.summary.auditCount,9);assert.equal(r.summary.categoryCount,3);assert.equal(r.metadata.formFactor,"mobile");assert.equal(r.metadata.warnings.length,1)});
test("reports missing version and URL",()=>{const x=fixture();delete x.lighthouseVersion;delete x.finalDisplayedUrl;delete x.requestedUrl;assert.deepEqual(L.analyzeLhr(x).issues.slice(0,2).map(i=>i.code),["version","url"])});
test("filters audits by state mode opportunity and query",()=>{const a=L.analyzeLhr(fixture()).audits;assert.equal(L.filterAudits(a,{state:"error"}).length,1);assert.equal(L.filterAudits(a,{mode:"manual"}).length,1);assert.equal(L.filterAudits(a,{opportunity:"yes"}).length,1);assert.equal(L.filterAudits(a,{query:"meta description"}).length,1)});
test("evaluates default metric category and transfer budgets",()=>{const b=L.evaluateBudgets(L.analyzeLhr(fixture()));assert.ok(b.failed.some(x=>x.id==="largest-contentful-paint"));assert.ok(b.failed.some(x=>x.id==="performance"));assert.ok(b.failed.some(x=>x.id==="total-byte-weight"));assert.ok(b.passed.some(x=>x.id==="total-blocking-time"))});
test("supports custom budgets",()=>{const b=L.evaluateBudgets(L.analyzeLhr(fixture()),{categoryMinimum:70,metrics:{"largest-contentful-paint":4000},totalBytes:3e6});assert.equal(b.failed.some(x=>x.id==="performance"),false);assert.equal(b.failed.some(x=>x.id==="largest-contentful-paint"),false)});
test("compares metric regressions and improvements",()=>{const before=fixture(),after=fixture();after.audits["largest-contentful-paint"].numericValue=2500;after.audits["total-blocking-time"].numericValue=240;const d=L.compareLhr(before,after);assert.equal(d.metrics.find(x=>x.id==="largest-contentful-paint").improvement,true);assert.equal(d.metrics.find(x=>x.id==="total-blocking-time").regression,true)});
test("compares category score direction",()=>{const before=fixture(),after=fixture();after.categories.performance.score=.8;after.categories.seo.score=.85;const d=L.compareLhr(before,after);assert.equal(d.categories.find(x=>x.id==="performance").improvement,true);assert.equal(d.categories.find(x=>x.id==="seo").regression,true)});
test("comparison accepts analyzed reports",()=>{const r=L.analyzeLhr(fixture()),d=L.compareLhr(r,r);assert.equal(d.summary.regressions,0);assert.ok(d.summary.unchanged>0)});
test("privacy cleaning removes details screenshots timing and URL secrets",()=>{const clean=L.sanitizeLhr(fixture());assert.equal("fullPageScreenshot"in clean,false);assert.equal("timing"in clean,false);assert.equal("details"in clean.audits["unused-javascript"],false);assert.equal(clean.finalDisplayedUrl,"https://example.com/app");assert.equal(clean.requestedUrl,"https://example.com/")});
test("privacy cleaning does not mutate input",()=>{const x=fixture(),before=JSON.stringify(x);L.sanitizeLhr(x);assert.equal(JSON.stringify(x),before)});
test("exports safe quoted CSV",()=>{const a=L.analyzeLhr(fixture()).audits;a[0].title="=cmd,\"x\"";const csv=L.auditsToCsv(a);assert.match(csv,/^"id","title"/);assert.match(csv,/"'=cmd,""x"""/);assert.equal(csv.endsWith("\n"),true)});
test("formats metric values",()=>{assert.equal(L.formatValue(1500,"millisecond"),"1.50 s");assert.equal(L.formatValue(.1234,"unitless"),"0.123");assert.equal(L.formatValue(2048,"byte"),"2.0 KB");assert.equal(L.formatValue(null,"ms"),"—")});
test("formats byte sizes",()=>{assert.equal(L.formatBytes(0),"0 B");assert.equal(L.formatBytes(1536),"1.5 KB");assert.equal(L.formatBytes(2*1024*1024),"2.0 MB")});
