version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm-maintenance:
        patterns:
          - "*"
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions-maintenance:
        patterns:
          - "*"
    open-pull-requests-limit: 3
