/**
 * Advanced SubStation Alpha (`.ass` / `.ssa`).
 *
 * subzen reads the `[Events]` section and keeps everything above it verbatim,
 * so styles, fonts and script metadata survive editing. Override blocks
 * (`{\an8\fad(200,200)}`) stay inside the cue text — they are markup, and
 * `core/text.js` knows how to look past them when measuring.
 *
 * @module formats/ass
 */

import { createCue } from '../core/cue.js';
import { parseTimecode, formatAssTime } from '../core/timecode.js';

export const id = 'ass';
export const extensions = ['.ass', '.ssa'];

const DEFAULT_HEADER = `[Script Info]
; Generated by subzen
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Source Han Sans SC,64,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,1,2,120,120,50,1
`;

const DEFAULT_FORMAT = [
  'Layer',
  'Start',
  'End',
  'Style',
  'Name',
  'MarginL',
  'MarginR',
  'MarginV',
  'Effect',
  'Text',
];

/**
 * @param {string} input
 * @returns {import('./index.js').Track}
 */
export function parse(input) {
  const text = String(input ?? '').replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
  const lines = text.split('\n');

  /** @type {import('../core/cue.js').Cue[]} */
  const cues = [];
  /** @type {string[]} */
  const warnings = [];
  /** @type {string[]} */
  const headerLines = [];

  let section = '';
  let fields = DEFAULT_FORMAT;
  let sawEvents = false;

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i];
    const sectionMatch = /^\s*\[([^\]]+)\]\s*$/.exec(line);

    if (sectionMatch) {
      section = sectionMatch[1].trim().toLowerCase();
      if (section === 'events') sawEvents = true;
      if (!sawEvents) headerLines.push(line);
      continue;
    }

    if (!sawEvents) {
      headerLines.push(line);
      continue;
    }

    if (section !== 'events') continue;

    const [rawKey, ...restParts] = splitOnce(line, ':');
    const key = rawKey.trim().toLowerCase();
    const rest = restParts.join(':');

    if (key === 'format') {
      fields = rest.split(',').map((f) => f.trim());
      continue;
    }

    if (key !== 'dialogue') continue;

    const values = splitFields(rest, fields.length);
    /** @type {Record<string,string>} */
    const record = {};
    fields.forEach((field, idx) => {
      record[field.toLowerCase()] = (values[idx] ?? '').trim();
    });

    const start = parseTimecode(record.start ?? '');
    const end = parseTimecode(record.end ?? '');
    if (Number.isNaN(start) || Number.isNaN(end)) {
      warnings.push(`line ${i + 1}: unreadable Dialogue timing`);
      continue;
    }

    const body = (record.text ?? '').split(/\\N/g);
    const cue = createCue({
      index: cues.length + 1,
      start,
      end,
      lines: body,
      style: record.style || 'Default',
      meta: {
        layer: record.layer ?? '0',
        name: record.name ?? '',
        marginL: record.marginl ?? '0',
        marginR: record.marginr ?? '0',
        marginV: record.marginv ?? '0',
        effect: record.effect ?? '',
      },
    });
    cues.push(cue);
  }

  if (!sawEvents) warnings.push('no [Events] section found');

  return {
    format: id,
    cues,
    meta: { assHeader: headerLines.join('\n').trim(), assFormat: fields },
    warnings,
  };
}

/**
 * @param {import('../core/cue.js').Cue[]} cues
 * @param {{ eol?: string, header?: string }} [options]
 * @returns {string}
 */
export function serialize(cues, options = {}) {
  const { eol = '\n', header } = options;

  const head = (header && header.trim() ? `${header.trim()}\n` : DEFAULT_HEADER).replace(/\n/g, eol);

  const events = [
    '[Events]',
    `Format: ${DEFAULT_FORMAT.join(', ')}`,
    ...cues.map((cue) => {
      const meta = /** @type {Record<string,string>} */ (cue.meta ?? {});
      return [
        `Dialogue: ${meta.layer ?? 0}`,
        formatAssTime(cue.start),
        formatAssTime(cue.end),
        cue.style || 'Default',
        meta.name ?? '',
        meta.marginL ?? '0',
        meta.marginR ?? '0',
        meta.marginV ?? '0',
        meta.effect ?? '',
        cue.lines.join('\\N'),
      ].join(',');
    }),
  ].join(eol);

  return `${head}${eol}${events}${eol}`;
}

/** @param {string} text @returns {number} */
export function sniff(text) {
  const head = text.slice(0, 2000);
  if (/^\s*\[Script Info\]/i.test(head)) return 1;
  if (/^\s*Dialogue:\s/m.test(head)) return 0.7;
  return 0;
}

/** @param {string} value @param {string} sep @returns {string[]} */
function splitOnce(value, sep) {
  const at = value.indexOf(sep);
  return at === -1 ? [value, ''] : [value.slice(0, at), value.slice(at + 1)];
}

/**
 * Split into exactly `count` fields — the final field (Text) keeps its commas.
 * @param {string} value
 * @param {number} count
 * @returns {string[]}
 */
function splitFields(value, count) {
  const out = [];
  let rest = value;
  for (let i = 0; i < count - 1; i += 1) {
    const at = rest.indexOf(',');
    if (at === -1) {
      out.push(rest);
      rest = '';
      continue;
    }
    out.push(rest.slice(0, at));
    rest = rest.slice(at + 1);
  }
  out.push(rest);
  return out;
}
