"use strict";
const assert = require("node:assert/strict");
const test = require("node:test");
const H = require("../src/core.js");

const HARDENED = [
  "HTTP/2 200", "Strict-Transport-Security: max-age=31536000; includeSubDomains",
  "X-Content-Type-Options: nosniff", "Content-Security-Policy: default-src 'self'; object-src 'none'; frame-ancestors 'none'",
  "Referrer-Policy: strict-origin-when-cross-origin", "Permissions-Policy: camera=(), microphone=(), geolocation=()"
].join("\n");

test("parses response status, lowercases names, and preserves duplicate values", () => { const p = H.parseHeaderBlock("HTTP/1.1 200 OK\nX-Test: a\nx-test: b"); assert.equal(p.statusLine, "HTTP/1.1 200 OK"); assert.deepEqual(p.headers.get("x-test"), ["a", "b"]); });
test("reports malformed lines, invalid names, and folded fields", () => { const p = H.parseHeaderBlock("bad\nBad Name: x\nX-Good: yes\n folded"); assert.equal(p.errors.length, 3); });
test("audits a hardened HTML baseline cleanly except optional information", () => { const r = H.auditHeaders(HARDENED, { url: "https://example.com", kind: "html" }); assert.equal(r.summary.errors, 0); assert.equal(r.summary.warnings, 0); assert.equal(r.summary.score, 100); });
test("detects missing HSTS, nosniff, CSP, framing, referrer and permissions policies", () => { const r = H.auditHeaders("Server: demo", { url: "https://example.com", kind: "html" }); const codes = r.findings.map(x => x.code); ["hsts.missing", "nosniff.missing", "csp.missing", "framing.missing", "referrer.missing", "permissions.missing"].forEach(code => assert.ok(codes.includes(code), code)); });
test("does not demand HSTS for HTTP context", () => { const r = H.auditHeaders("X-Content-Type-Options: nosniff", { url: "http://localhost", kind: "api" }); assert.equal(r.findings.some(x => x.code.startsWith("hsts.")), false); });
test("validates HSTS max-age and duplicate singleton fields", () => { const r = H.auditHeaders("Strict-Transport-Security: max-age=60\nStrict-Transport-Security: max-age=60\nX-Content-Type-Options: nosniff", { url: "https://x.test", kind: "api" }); assert.ok(r.findings.some(x => x.code === "hsts.short-max-age")); assert.ok(r.findings.some(x => x.code === "header.duplicate")); });
test("finds CSP script hazards and report-only policies", () => { const r = H.auditHeaders("X-Content-Type-Options: nosniff\nContent-Security-Policy-Report-Only: default-src 'self'\nContent-Security-Policy: script-src * 'unsafe-eval'\nReferrer-Policy: no-referrer\nPermissions-Policy: camera=()", { url: "http://x.test", kind: "html" }); assert.ok(r.findings.some(x => x.code === "csp.unsafe-eval")); assert.ok(r.findings.some(x => x.code === "csp.wildcard-script")); });
test("detects unsafe CORS combinations and missing Vary Origin", () => { let r = H.auditHeaders("X-Content-Type-Options: nosniff\nAccess-Control-Allow-Origin: *\nAccess-Control-Allow-Credentials: true", { url: "http://api.test", kind: "api" }); assert.ok(r.findings.some(x => x.code === "cors.wildcard-credentials")); r = H.auditHeaders("X-Content-Type-Options: nosniff\nAccess-Control-Allow-Origin: https://app.test", { url: "http://api.test", kind: "api" }); assert.ok(r.findings.some(x => x.code === "cors.vary-origin")); });
test("audits sensitive caching, public cookie responses, and disclosure", () => { const r = H.auditHeaders("X-Content-Type-Options: nosniff\nCache-Control: public, max-age=60\nSet-Cookie: sid=x\nX-Powered-By: Demo", { url: "http://x.test", kind: "api", sensitive: true }); assert.ok(r.findings.some(x => x.code === "cache.sensitive")); assert.ok(r.findings.some(x => x.code === "cache.public-cookie")); assert.ok(r.findings.some(x => x.code === "disclosure.x-powered-by")); });
test("evaluates cross-origin isolation and CORP values", () => { const good = H.auditHeaders(HARDENED + "\nCross-Origin-Opener-Policy: same-origin\nCross-Origin-Embedder-Policy: require-corp", { url: "https://x.test", kind: "html", isolation: true }); assert.equal(good.summary.crossOriginIsolated, true); const bad = H.auditHeaders(HARDENED + "\nCross-Origin-Resource-Policy: nope", { url: "https://x.test", kind: "html", isolation: true }); assert.ok(bad.findings.some(x => x.code === "isolation.coop")); assert.ok(bad.findings.some(x => x.code === "corp.invalid")); });
test("compares header snapshots and reports score delta", () => { const diff = H.compareHeaders(HARDENED, "X-Content-Type-Options: nosniff", { url: "https://x.test", kind: "html" }); assert.ok(diff.changes.some(x => x.code === "header.removed")); assert.ok(diff.summary.errors > 0); assert.ok(diff.summary.scoreDelta < 0); });
test("generates contextual baselines", () => { const html = H.generateBaseline({ kind: "html", sensitive: true, isolation: true }); assert.match(html, /Content-Security-Policy/); assert.match(html, /Cache-Control: no-store/); assert.match(html, /Cross-Origin-Embedder-Policy/); const api = H.generateBaseline({ kind: "api" }); assert.doesNotMatch(api, /Permissions-Policy/); });
test("filters and exports findings deterministically", () => { const report = H.auditHeaders("", { url: "https://x.test", kind: "html" }); assert.equal(H.filterFindings(report.findings, { severity: "error" }).every(x => x.severity === "error"), true); assert.ok(H.filterFindings(report.findings, { query: "MIME" }).some(x => x.code === "nosniff.missing")); assert.match(H.formatMarkdown(report), /# Header Sentinel/); });
