"use strict";
const assert = require("node:assert/strict");
const test = require("node:test");
const C = require("../src/core.js");

function spec(overrides = {}) {
  return { openapi: "3.1.0", info: { title: "Example" }, paths: { "/pets/{id}": { parameters: [{ name: "id", in: "path", required: true, schema: { type: "string" } }], get: { operationId: "getPet", responses: { "200": { description: "ok", content: { "application/json": { schema: { $ref: "#/components/schemas/Pet" } } } }, "404": { description: "missing" } } } }, "/health": { get: { operationId: "health", responses: { "200": { description: "ok" } } } } }, components: { schemas: { Pet: { type: "object", required: ["id", "name"], properties: { id: { type: "string" }, name: { type: "string" }, tags: { type: "array", items: { type: "string" } } } } } }, ...overrides };
}

test("parses JSON, BOM input, refs, and normalized operations", () => { const parsed = C.parseDocument("\uFEFF" + JSON.stringify(spec())); const pet = parsed.operations.find(x => x.key === "GET /pets/{id}"); assert.equal(parsed.version, "3.1.0"); assert.equal(parsed.operations.length, 2); assert.equal(pet.parameters[0].required, true); assert.equal(pet.responses[0].schema.type, "object"); assert.ok(pet.responses[0].schema.properties.name); });
test("rejects empty, malformed, non-object, and missing paths documents", () => { assert.throws(() => C.parseDocument(""), /empty/); assert.throws(() => C.parseDocument("{bad}"), /Invalid/); assert.throws(() => C.parseDocument([]), /root/); assert.throws(() => C.parseDocument({ openapi: "3.1.0" }), /paths/); });
test("rejects unsupported OpenAPI and Swagger versions", () => { assert.throws(() => C.parseDocument({ openapi: "2.0", paths: {} }), /OpenAPI 3/); assert.throws(() => C.parseDocument({ swagger: "1.2", paths: {} }), /Swagger 2/); });
test("supports Swagger 2 body parameters and path-level parameters", () => { const parsed = C.parseDocument({ swagger: "2.0", info: {}, paths: { "/x": { post: { parameters: [{ in: "body", name: "payload", required: true, schema: { type: "object" } }], responses: { "200": { description: "ok" } } } } } }); assert.equal(parsed.operations[0].requestBody.required, true); });
test("supports Swagger 2 response schemas", () => { const parsed = C.parseDocument({ swagger: "2.0", paths: { "/x": { get: { responses: { "200": { description: "ok", schema: { type: "array", items: { type: "string" } } } } } } } }); assert.equal(parsed.operations[0].responses[0].schema.type, "array"); });
test("detects removed and added operations", () => { const before = spec(); const after = spec({ paths: { "/pets/{id}": before.paths["/pets/{id}"] , "/new": { get: { responses: { "204": { description: "ok" } } } } } }); const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "operation.removed" && x.path === "GET /health")); assert.ok(diff.changes.some(x => x.code === "operation.added" && x.path === "GET /new")); });
test("detects required parameter additions and type changes", () => { const before = spec(); const after = spec(); after.paths["/pets/{id}"].get.parameters = [{ name: "limit", in: "query", required: true, schema: { type: "integer" } }]; after.paths["/pets/{id}"].parameters[0].schema = { type: "integer" }; const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "parameter.added" && x.severity === "breaking")); assert.ok(diff.changes.some(x => x.code === "parameter.type-changed")); });
test("detects request body required and schema changes", () => { const before = spec(); before.paths["/pets/{id}"].post = { requestBody: { content: { "application/json": { schema: { type: "object", properties: { name: { type: "string" } } } } } }, responses: { "201": { description: "created" } } }; const after = JSON.parse(JSON.stringify(before)); after.paths["/pets/{id}"].post.requestBody.required = true; after.paths["/pets/{id}"].post.requestBody.content["application/json"].schema.required = ["name"]; const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "request-body.required")); assert.ok(diff.changes.some(x => x.code === "schema.required-added")); });
test("detects response status and required property removal", () => { const before = spec(); const after = spec(); delete after.paths["/pets/{id}"].get.responses["404"]; after.components.schemas.Pet.required = ["id"]; delete after.components.schemas.Pet.properties.name; const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "response.removed")); assert.ok(diff.changes.some(x => x.code === "schema.property-removed" && x.severity === "breaking")); assert.ok(diff.changes.some(x => x.code === "schema.required-removed" && x.severity === "breaking")); });
test("detects response media type changes", () => { const before = spec(); const after = spec(); const response = after.paths["/pets/{id}"].get.responses["200"]; response.content["application/xml"] = response.content["application/json"]; delete response.content["application/json"]; const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "response.media-changed" && x.severity === "breaking")); });
test("detects type, enum, optional additions, and security changes", () => { const before = spec({ security: [] }); before.components.schemas.Pet.properties.id = { type: "string", enum: ["a", "b"] }; const after = spec({ security: [{ bearerAuth: [] }] }); after.components.schemas.Pet.properties.id = { type: "integer", enum: [1, 2] }; after.components.schemas.Pet.properties.extra = { type: "string" }; const diff = C.compareDocuments(before, after); assert.ok(diff.changes.some(x => x.code === "schema.type-changed")); assert.ok(diff.changes.some(x => x.code === "schema.enum-removed")); assert.ok(diff.changes.some(x => x.code === "schema.property-added")); assert.ok(diff.changes.some(x => x.code === "security-changed")); });
test("filters changes deterministically and formats Markdown", () => { const diff = C.compareDocuments(spec(), spec({ paths: {} })); assert.equal(C.filterChanges(diff.changes, { severity: "breaking" }).every(x => x.severity === "breaking"), true); assert.equal(C.filterChanges(diff.changes, { query: "operation removed" }).length, 2); const md = C.formatMarkdown(diff); assert.match(md, /# API Contract Diff/); assert.match(md, /BREAKING/); });
test("does not mutate source documents", () => { const before = spec(); const snapshot = JSON.stringify(before); C.compareDocuments(before, spec()); assert.equal(JSON.stringify(before), snapshot); });
