const Core = window.SarifCompass;
const MAX_FILE_SIZE = 25 * 1024 * 1024;
const state = { report: null, selectedId: null, fileName: "report.sarif", comparison: null, compareName: "" };
const $ = (id) => document.getElementById(id);
const elements = { importPanel: $("import-panel"), dashboard: $("dashboard"), status: $("status"), primaryFile: $("primary-file"), compareFile: $("compare-file"), drop: $("drop-zone"), sample: $("sample"), theme: $("theme"), fileName: $("file-name"), reportMeta: $("report-meta"), openAnother: $("open-another"), compare: $("compare"), csv: $("csv"), sanitize: $("sanitize"), resultCount: $("result-count"), errorCount: $("error-count"), toolCount: $("tool-count"), fileCount: $("file-count"), newCount: $("new-count"), diffPanel: $("diff-panel"), compareName: $("compare-name"), diffSummary: $("diff-summary"), diffList: $("diff-list"), closeDiff: $("close-diff"), search: $("search"), levelFilter: $("level-filter"), toolFilter: $("tool-filter"), ruleFilter: $("rule-filter"), baselineFilter: $("baseline-filter"), suppressionFilter: $("suppression-filter"), flowFilter: $("flow-filter"), resetFilters: $("reset-filters"), resultList: $("result-list"), resultEmpty: $("result-empty"), visibleCount: $("visible-count"), notices: $("notices"), noticeEmpty: $("notice-empty"), noticeCount: $("notice-count"), detail: $("detail") };

function sampleRule(id, name, level, tags, severity) { return { id, name, shortDescription: { text: name }, fullDescription: { text: `Review ${name.toLowerCase()} findings before release.` }, help: { text: `Remediation guidance for ${id}.` }, helpUri: `https://rules.example.invalid/${id}`, defaultConfiguration: { level }, properties: { tags, precision: "high", ...(severity ? { "security-severity": severity } : {}) } }; }
function sampleLocation(uri, line, snippet) { return { physicalLocation: { artifactLocation: { uri, uriBaseId: "SRCROOT" }, region: { startLine: line, startColumn: 3, endLine: line, endColumn: 18, snippet: { text: snippet } } } }; }
function sampleResult(ruleId, level, message, uri, line, fingerprint, options = {}) {
  const value = { ruleId, level, message: { text: message }, locations: [sampleLocation(uri, line, options.snippet || message)], partialFingerprints: { primaryLocationLineHash: fingerprint }, baselineState: options.baseline || "unchanged" };
  if (options.suppressed) value.suppressions = [{ kind: "external", status: "underReview", justification: "Awaiting security review" }];
  if (options.flow) value.codeFlows = [{ threadFlows: [{ locations: [{ executionOrder: 1, location: sampleLocation("src/http/request.js", 14, "const input = request.query.id") }, { executionOrder: 2, importance: "essential", location: sampleLocation(uri, line, options.snippet || message) }] }] }];
  if (options.fix) value.fixes = [{ description: { text: "Suggested replacement" }, artifactChanges: [] }];
  return value;
}

function sampleSarif(updated = false) {
  const codeRules = [sampleRule("js/sql-injection", "SQL query built from user input", "error", ["security", "external/cwe/cwe-089"], "9.1"), sampleRule("js/hardcoded-credential", "Hardcoded credential", "warning", ["security", "external/cwe/cwe-798"], "8.0"), sampleRule("js/path-injection", "Uncontrolled path expression", "warning", ["security", "external/cwe/cwe-022"], "7.5"), sampleRule("js/xss", "Unescaped user-controlled HTML", "error", ["security", "external/cwe/cwe-079"], "8.6")];
  const codeResults = [sampleResult("js/sql-injection", updated ? "warning" : "error", updated ? "Query now uses a partial parameterization" : "User input reaches a database query", "src/db/orders.js", updated ? 48 : 42, "sql-stable", { baseline: "new", flow: true, fix: true, snippet: "db.query('SELECT ' + userInput)" }), sampleResult("js/path-injection", "warning", "User input reaches a file path", "src/files/export.js", 31, "path-stable", { baseline: "unchanged", flow: true })];
  if (updated) codeResults.push(sampleResult("js/xss", "error", "User-controlled HTML reaches an unsafe sink", "src/views/profile.js", 77, "xss-new", { baseline: "new", flow: true }));
  else codeResults.push(sampleResult("js/hardcoded-credential", "warning", "Credential-like value committed to source", "src/config/legacy.js", 9, "secret-old", { baseline: "unchanged", suppressed: true }));
  const lintRules = [sampleRule("no-eval", "Unexpected eval", "warning", ["recommended"]), sampleRule("eqeqeq", "Expected strict equality", "note", ["style"])];
  const lintResults = [sampleResult("no-eval", "warning", "Unexpected use of eval", "src/plugins/loader.js", 23, "eval-stable", { baseline: "unchanged" }), sampleResult("eqeqeq", "note", "Use === instead of ==", "src/utils/match.js", 12, "eq-stable", { baseline: "unchanged", fix: true })];
  return { version: "2.1.0", $schema: "https://json.schemastore.org/sarif-2.1.0.json", runs: [{ tool: { driver: { name: "CodeQL", semanticVersion: "2.23.0", rules: codeRules } }, originalUriBaseIds: { SRCROOT: { uri: "file:///workspace/atlas-app/" } }, results: codeResults }, { tool: { driver: { name: "ESLint", semanticVersion: "9.34.0", rules: lintRules } }, originalUriBaseIds: { SRCROOT: { uri: "file:///workspace/atlas-app/" } }, results: lintResults }] };
}

function setStatus(message, kind = "") { elements.status.textContent = message; elements.status.className = `status ${kind}`.trim(); }
function option(value, label) { const item = document.createElement("option"); item.value = value; item.textContent = label; return item; }
function replaceOptions(select, values, label) { select.replaceChildren(option("all", label)); values.forEach((value) => select.append(option(value, value))); }
function populateFilters() { replaceOptions(elements.toolFilter, [...new Set(state.report.results.map((item) => item.tool))].sort(), "All tools"); replaceOptions(elements.ruleFilter, [...new Set(state.report.results.map((item) => item.ruleId))].sort(), "All rules"); replaceOptions(elements.baselineFilter, [...new Set(state.report.results.map((item) => item.baselineState))].sort(), "Any baseline"); }
function resetFilters() { elements.search.value = ""; elements.levelFilter.value = "all"; elements.toolFilter.value = "all"; elements.ruleFilter.value = "all"; elements.baselineFilter.value = "all"; elements.suppressionFilter.value = "all"; elements.flowFilter.value = "all"; }

function loadPrimary(source, fileName) {
  try { state.report = Core.analyzeSarif(source); state.fileName = fileName || "report.sarif"; state.selectedId = state.report.results.find((item) => item.level === "error")?.id || state.report.results[0]?.id || null; state.comparison = null; populateFilters(); resetFilters(); elements.importPanel.hidden = true; elements.dashboard.hidden = false; elements.diffPanel.hidden = true; setStatus(""); render(); }
  catch (error) { setStatus(error instanceof Error ? error.message : "Could not analyze this SARIF report.", "error"); }
}
function loadComparison(source, fileName) { try { state.comparison = Core.compareSarif(state.report, source); state.compareName = fileName || "comparison.sarif"; elements.diffPanel.hidden = false; setStatus(`Compared current report with ${state.compareName}.`, "ok"); renderDiff(); elements.diffPanel.scrollIntoView({ behavior: "smooth", block: "nearest" }); } catch (error) { setStatus(error instanceof Error ? error.message : "Could not compare this SARIF report.", "error"); } }

function render() { const { summary } = state.report; elements.fileName.textContent = state.fileName; elements.reportMeta.textContent = `SARIF ${state.report.document.version || "unknown"} · ${summary.runCount} run(s) · ${summary.ruleCount} rules · ${state.report.issues.length} parser ${state.report.issues.length === 1 ? "notice" : "notices"}`; elements.resultCount.textContent = String(summary.resultCount); elements.errorCount.textContent = String(summary.levelCounts.error); elements.toolCount.textContent = String(summary.toolCount); elements.fileCount.textContent = String(summary.fileCount); elements.newCount.textContent = String(summary.baselineNewCount); renderResults(); renderNotices(); renderDetail(); }
function filterOptions() { return { query: elements.search.value.trim(), level: elements.levelFilter.value, tool: elements.toolFilter.value, rule: elements.ruleFilter.value, baseline: elements.baselineFilter.value, suppressed: elements.suppressionFilter.value, hasFlow: elements.flowFilter.value }; }
function filteredResults() { return Core.filterResults(state.report.results, filterOptions()); }

function renderResults() {
  const visible = filteredResults(); elements.resultList.replaceChildren(); elements.visibleCount.textContent = String(visible.length); elements.resultEmpty.hidden = visible.length !== 0;
  visible.forEach((result) => { const button = document.createElement("button"); button.type = "button"; button.className = "result-row"; button.setAttribute("role", "listitem"); if (result.id === state.selectedId) button.classList.add("selected"); const level = document.createElement("span"); level.className = `level ${result.level}`; level.textContent = result.level; const copy = document.createElement("span"); copy.className = "result-copy"; const message = document.createElement("strong"); message.textContent = result.message || "(no message)"; const rule = document.createElement("small"); rule.textContent = result.ruleId + (result.suppressed ? " · suppressed" : ""); copy.append(message, rule); const tool = document.createElement("span"); tool.className = "metric"; tool.textContent = result.tool; const artifact = document.createElement("span"); artifact.className = "metric"; artifact.textContent = `${result.primaryLocation.uri}${Core.formatRegion(result.primaryLocation.region) ? `:${Core.formatRegion(result.primaryLocation.region)}` : ""}`; const baseline = document.createElement("span"); baseline.className = `baseline ${result.baselineState}`; baseline.textContent = result.baselineState; const flow = document.createElement("span"); flow.className = result.codeFlowSteps.length ? "metric flow-badge" : "metric"; flow.textContent = result.codeFlowSteps.length ? String(result.codeFlowSteps.length) : "—"; button.append(level, copy, tool, artifact, baseline, flow); button.addEventListener("click", () => { state.selectedId = result.id; renderResults(); renderDetail(); }); elements.resultList.append(button); });
}

function renderNotices() { elements.notices.replaceChildren(); elements.noticeCount.textContent = String(state.report.issues.length); elements.noticeEmpty.hidden = state.report.issues.length !== 0; state.report.issues.forEach((issue) => { const row = document.createElement("div"); row.className = `notice ${issue.severity}`; const body = document.createElement("span"); const title = document.createElement("strong"); title.textContent = issue.message; const path = document.createElement("small"); path.textContent = issue.path; body.append(title, path); row.append(body); elements.notices.append(row); }); }
function fact(label, value) { const item = document.createElement("div"); item.className = "fact"; const key = document.createElement("span"); key.textContent = label; const output = document.createElement("strong"); output.textContent = String(value || "—"); item.append(key, output); return item; }
function pair(label, value) { const row = document.createElement("div"); row.className = "pair"; const key = document.createElement("span"); key.textContent = label; const output = document.createElement("code"); output.textContent = String(value || "—"); row.append(key, output); return row; }
function heading(text) { const item = document.createElement("h3"); item.textContent = text; return item; }

function renderDetail() {
  elements.detail.replaceChildren(); const result = state.report.results.find((item) => item.id === state.selectedId); if (!result) { const empty = document.createElement("p"); empty.className = "empty"; empty.textContent = "Select a result to inspect it."; elements.detail.append(empty); return; }
  const message = document.createElement("h3"); message.className = "detail-message"; message.textContent = result.message || "(no message)"; const location = document.createElement("p"); location.className = "detail-location"; location.textContent = Core.formatLocation(result.primaryLocation); const facts = document.createElement("div"); facts.className = "facts"; facts.append(fact("Level", result.level), fact("Rule", result.ruleId), fact("Tool", `${result.tool}${result.toolVersion ? ` ${result.toolVersion}` : ""}`), fact("Baseline", result.baselineState), fact("Suppression", result.suppressed ? "Suppressed" : "Active"), fact("Autofix", result.hasFix ? "Available" : "None")); elements.detail.append(message, location, facts);
  if (result.primaryLocation.region.snippet) { const snippet = document.createElement("pre"); snippet.className = "snippet"; snippet.textContent = result.primaryLocation.region.snippet; elements.detail.append(heading("Source snippet"), snippet); }
  if (result.rule) { elements.detail.append(heading("Rule metadata"), pair("Name", result.rule.name), pair("Description", result.rule.shortDescription), pair("Tags", result.rule.tags.join(", ")), pair("Precision", result.rule.precision), pair("Security severity", result.rule.securitySeverity === null ? "—" : result.rule.securitySeverity), pair("Help URI", result.rule.helpUri)); }
  if (result.suppressions.length) { elements.detail.append(heading("Suppressions")); result.suppressions.forEach((item) => elements.detail.append(pair(`${item.kind || "suppression"} · ${item.status || "unspecified"}`, item.justification))); }
  if (result.codeFlowSteps.length) { elements.detail.append(heading(`Code flow (${result.codeFlowSteps.length} steps)`)); const list = document.createElement("div"); list.className = "flow-list"; result.codeFlowSteps.forEach((step, index) => { const row = document.createElement("div"); row.className = "flow-step"; const number = document.createElement("b"); number.textContent = String(index + 1); const body = document.createElement("span"); const where = document.createElement("strong"); where.textContent = `${step.uri}${Core.formatRegion(step.region) ? `:${Core.formatRegion(step.region)}` : ""}`; const detail = document.createElement("small"); detail.textContent = [step.message, step.importance].filter(Boolean).join(" · ") || "Flow step"; body.append(where, detail); row.append(number, body); list.append(row); }); elements.detail.append(list); }
}

function summaryItem(label, value) { const item = document.createElement("div"); const key = document.createElement("span"); key.textContent = label; const output = document.createElement("strong"); output.textContent = String(value); item.append(key, output); return item; }
function diffItem(result, detail) { const item = document.createElement("div"); item.className = "diff-item"; const title = document.createElement("strong"); title.textContent = `${result.ruleId} · ${result.message}`; const copy = document.createElement("span"); copy.textContent = detail || Core.formatLocation(result.primaryLocation); item.append(title, copy); return item; }
function renderDiff() { if (!state.comparison) return; const diff = state.comparison; elements.compareName.textContent = state.compareName; elements.diffSummary.replaceChildren(summaryItem("Added", diff.summary.added), summaryItem("Removed", diff.summary.removed), summaryItem("Updated", diff.summary.updated), summaryItem("Unchanged", diff.summary.unchanged)); elements.diffList.replaceChildren(); const groups = [{ title: "Added", items: diff.added.map((item) => diffItem(item)) }, { title: "Removed", items: diff.removed.map((item) => diffItem(item)) }, { title: "Updated", items: diff.updated.map((item) => diffItem(item.after, item.changes.map((change) => `${change.field}: ${change.before} → ${change.after}`).join(" · "))) }]; groups.forEach((group) => { const section = document.createElement("section"); section.className = "diff-group"; const title = document.createElement("h3"); title.textContent = `${group.title} (${group.items.length})`; section.append(title); if (!group.items.length) { const empty = document.createElement("p"); empty.className = "empty"; empty.textContent = "None"; section.append(empty); } else group.items.forEach((item) => section.append(item)); elements.diffList.append(section); }); }

function readFile(file, callback) { if (!file) return; if (file.size > MAX_FILE_SIZE) { setStatus("Choose a SARIF or JSON file no larger than 25 MB.", "error"); return; } const reader = new FileReader(); reader.onload = () => callback(String(reader.result), file.name); reader.onerror = () => setStatus("The browser could not read this file.", "error"); reader.readAsText(file); }
function openPrimary() { elements.primaryFile.value = ""; elements.primaryFile.click(); } function openCompare() { elements.compareFile.value = ""; elements.compareFile.click(); }
function baseName(name) { return name.replace(/\.(?:sarif|json)$/i, "").replace(/[^a-z0-9._-]+/gi, "-").replace(/^-+|-+$/g, "") || "report"; }
function download(name, content, type) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }

elements.primaryFile.addEventListener("change", () => readFile(elements.primaryFile.files[0], loadPrimary)); elements.compareFile.addEventListener("change", () => readFile(elements.compareFile.files[0], loadComparison)); elements.drop.addEventListener("click", openPrimary); elements.drop.addEventListener("dragover", (event) => { event.preventDefault(); elements.drop.classList.add("dragging"); }); elements.drop.addEventListener("dragleave", () => elements.drop.classList.remove("dragging")); elements.drop.addEventListener("drop", (event) => { event.preventDefault(); elements.drop.classList.remove("dragging"); readFile(event.dataTransfer.files[0], loadPrimary); }); elements.sample.addEventListener("click", () => loadPrimary(sampleSarif(), "atlas-app-baseline.sarif")); elements.openAnother.addEventListener("click", openPrimary); elements.compare.addEventListener("click", openCompare); elements.closeDiff.addEventListener("click", () => { state.comparison = null; elements.diffPanel.hidden = true; setStatus(""); }); elements.theme.addEventListener("click", () => { document.documentElement.dataset.theme = document.documentElement.dataset.theme === "dark" ? "light" : "dark"; });
[elements.search, elements.levelFilter, elements.toolFilter, elements.ruleFilter, elements.baselineFilter, elements.suppressionFilter, elements.flowFilter].forEach((control) => control.addEventListener("input", renderResults)); elements.resetFilters.addEventListener("click", () => { resetFilters(); renderResults(); }); elements.csv.addEventListener("click", () => download(`${baseName(state.fileName)}-results.csv`, Core.resultsToCsv(filteredResults()), "text/csv;charset=utf-8")); elements.sanitize.addEventListener("click", () => { const clean = Core.sanitizeSarif(state.report.document); download(`${baseName(state.fileName)}-privacy-clean.sarif`, JSON.stringify(clean, null, 2) + "\n", "application/sarif+json"); setStatus("Privacy-clean export created: snippets, fixes, invocation data, web traffic, URI bases, artifact contents, and URI secrets removed.", "ok"); });
const sampleMode = new URLSearchParams(window.location.search).get("sample"); if (sampleMode !== null) { loadPrimary(sampleSarif(), "atlas-app-baseline.sarif"); if (sampleMode === "compare") loadComparison(sampleSarif(true), "atlas-app-current.sarif"); }
