const S = window.SriStudio; const $ = (id) => document.getElementById(id); const e = { base: $('base'), require: $('require'), html: $('html'), content: $('content'), audit: $('audit'), sample: $('sample'), hash: $('hash'), compare: $('compare'), markdown: $('markdown'), json: $('json'), generated: $('generated'), previous: null, status: $('status'), report: $('report'), resources: $('resources'), errors: $('errors'), warnings: $('warnings'), info: $('info'), changes: $('changes'), severity: $('severity'), query: $('query'), findings: $('findings'), inventory: $('inventory') }; let report;
const SAMPLE = '<script src="/app.js" integrity="sha384-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="></script>\n<script src="https://cdn.example.com/widget.js"></script>\n<link rel="stylesheet" href="https://cdn.example.com/site.css" integrity="sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="></link>';
function setStatus(message, bad = false) { e.status.textContent = message; e.status.className = bad ? 'error' : ''; }
function opts() { return { baseUrl: e.base.value, requireIntegrity: e.require.checked }; }
function download(name, data, type) { const url = URL.createObjectURL(new Blob([data], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function render() { if (!report) return; const s = report.summary; e.report.hidden = false; e.resources.textContent = s.resources; e.errors.textContent = s.errors; e.warnings.textContent = s.warnings; e.info.textContent = s.info; e.changes.textContent = report.changes ? report.changes.length : 0; const items = S.filterFindings(report.findings, { severity: e.severity.value, query: e.query.value }); e.findings.replaceChildren(); if (!items.length) { const empty = document.createElement('p'); empty.textContent = 'No findings match this filter.'; e.findings.append(empty); } items.forEach((item) => { const row = document.createElement('div'); row.className = `finding ${item.severity}`; const b = document.createElement('b'); const span = document.createElement('span'); b.textContent = `${item.severity.toUpperCase()} | ${item.message}`; span.textContent = `${item.code} @ ${item.resource}${item.detail ? ` · ${item.detail}` : ''}`; row.append(b, span); e.findings.append(row); }); e.inventory.replaceChildren(); report.resources.forEach((resource) => { const row = document.createElement('div'); row.className = 'resource'; const b = document.createElement('b'); const span = document.createElement('span'); b.textContent = `${resource.kind} · ${resource.url}`; span.textContent = resource.integrity || 'no integrity'; row.append(b, span); e.inventory.append(row); }); }
function audit() { report = S.auditResources(e.html.value, opts()); setStatus(`${report.summary.resources} resources inspected.`); render(); }
async function generate() { if (!e.content.value) { setStatus('Paste exact resource content before generating a hash.', true); return; } try { const algorithms = [...document.querySelectorAll('.hash-actions input:checked')].map((x) => x.value); e.generated.textContent = await S.generateIntegrity(e.content.value, algorithms); setStatus('Integrity expression generated.'); } catch (error) { setStatus(error.message, true); } }
function compare() { const previous = prompt('Paste the previous HTML snapshot to compare:'); if (previous === null) return; const diff = S.compareDocuments(previous, e.html.value, opts()); report = diff.after; report.findings = report.findings.concat(diff.changes); report.changes = diff.changes; setStatus(`${diff.changes.length} resource changes found.`); render(); }
e.audit.onclick = audit; e.sample.onclick = () => { e.html.value = SAMPLE; audit(); }; e.hash.onclick = generate; e.compare.onclick = compare; e.markdown.onclick = () => { if (report) download('sri-studio.md', S.formatMarkdown(report), 'text/markdown'); }; e.json.onclick = () => { if (report) download('sri-studio.json', JSON.stringify({ summary: report.summary, findings: report.findings }, null, 2), 'application/json'); }; [e.severity, e.query].forEach((input) => { input.oninput = render; }); e.sample.click();
