"use strict";
const assert = require("node:assert/strict"); const test = require("node:test"); const T = require("../src/core.js");
function jaeger() { return { data: [{ traceID: "trace-1", processes: { p1: { serviceName: "web" }, p2: { serviceName: "api" } }, spans: [{ traceID: "trace-1", spanID: "root", operationName: "GET /", processID: "p1", startTime: 1000000, duration: 100000, tags: [{ key: "http.status_code", value: 200 }] }, { traceID: "trace-1", spanID: "child", references: [{ refType: "CHILD_OF", spanID: "root" }], operationName: "query", processID: "p2", startTime: 1050000, duration: 700000, tags: [{ key: "error", value: true }] }] }] }; }
function otlp() { return { resourceSpans: [{ resource: { attributes: [{ key: "service.name", value: { stringValue: "checkout" } }] }, scopeSpans: [{ spans: [{ traceId: "t1", spanId: "s1", name: "POST /pay", startTimeUnixNano: "1000000000", endTimeUnixNano: "1200000000", status: { code: 2 }, attributes: [{ key: "http.response.status_code", value: { intValue: 503 } }] }] }] }] }; }
test("parses empty, malformed, and unsupported trace documents", () => { assert.throws(() => T.analyzeTrace(""), /empty/); assert.throws(() => T.analyzeTrace("{bad}"), /Invalid/); const r = T.analyzeTrace({ nope: true }); assert.equal(r.summary.spans, 0); });
test("normalizes Jaeger traces, services, errors, and critical path", () => { const r = T.analyzeTrace(jaeger()); assert.equal(r.format, "jaeger"); assert.equal(r.summary.spans, 2); assert.equal(r.summary.services, 2); assert.equal(r.summary.errors, 1); assert.equal(r.traces[0].criticalPath.spans.length, 2); assert.equal(r.services[0].service, "api"); });
test("normalizes OTLP resource spans and status/error attributes", () => { const r = T.analyzeTrace(otlp()); assert.equal(r.format, "otlp"); assert.equal(r.summary.errors, 2); assert.equal(r.services[0].service, "checkout"); assert.equal(r.spans[0].httpStatus, 503); });
test("detects slow spans, orphan parents, and HTTP failures", () => { const doc = { spans: [{ traceId: "t", spanId: "s", parentSpanId: "missing", service: "api", name: "slow", startTime: 1000, endTime: 3000, attributes: { "http.status_code": 500 } }] }; const r = T.analyzeTrace(doc); assert.ok(r.findings.some(x => x.code === "span.slow")); assert.ok(r.findings.some(x => x.code === "span.orphan")); assert.ok(r.findings.some(x => x.code === "http.status")); });
test("supports flat spans and stable duration formatting", () => { const r = T.analyzeTrace({ spans: [{ traceId: "t", spanId: "s", service: "worker", name: "job", startTime: 1, duration: 5 }] }); assert.equal(r.format, "flat"); assert.equal(r.summary.spans, 1); assert.equal(T.formatDuration(1500), "1.50 s"); assert.equal(T.formatDuration(.5), "500.0 µs"); });
test("compares service regressions, errors, and longest trace duration", () => { const before = { spans: [{ traceId: "t", spanId: "s", service: "api", name: "x", startTime: 1000, duration: 100 }] }; const after = { spans: [{ traceId: "t", spanId: "s", service: "api", name: "x", startTime: 1000, duration: 500, attributes: { error: true } }] }; const r = T.compareTraces(before, after); assert.ok(r.changes.some(x => x.code === "service.regression")); assert.ok(r.changes.some(x => x.code === "service.errors")); assert.ok(r.changes.some(x => x.code === "trace.regression")); });
test("reports added and removed services", () => { const r = T.compareTraces({ spans: [{ traceId: "t", spanId: "a", service: "old", startTime: 1, duration: 1 }] }, { spans: [{ traceId: "t", spanId: "b", service: "new", startTime: 1, duration: 1 }] }); assert.ok(r.changes.some(x => x.code === "service.added")); assert.ok(r.changes.some(x => x.code === "service.removed")); });
test("filters findings, exports Markdown, and does not mutate input", () => { const input = jaeger(); const snapshot = JSON.stringify(input); const r = T.analyzeTrace(input); assert.equal(JSON.stringify(input), snapshot); assert.equal(T.filterFindings(r.findings, { severity: "error" }).every(x => x.severity === "error"), true); assert.match(T.formatMarkdown(r), /# Trace Atlas/); });
