const J = window.JwtTrust;
const $ = (id) => document.getElementById(id);
const e = { token: $("token"), keys: $("keys"), issuer: $("issuer"), audience: $("audience"), skew: $("skew"), inspect: $("inspect"), verify: $("verify"), sample: $("sample"), markdown: $("markdown"), json: $("json"), status: $("status"), signature: $("signature"), errors: $("errors"), warnings: $("warnings"), info: $("info"), header: $("header"), payload: $("payload"), findings: $("findings"), key: $("key") };
let report = null;
const SAMPLE = { token: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRlbW8ta2V5IiwidHlwIjoiSldUIn0.eyJzdWIiOiJhbGljZSIsImlzcyI6Imh0dHBzOi8vaWRwLmV4YW1wbGUuY29tIiwiYXVkIjoiYXBpIiwiZXhwIjo0M10.demo", keys: JSON.stringify({ keys: [{ kty: "RSA", kid: "demo-key", alg: "RS256", use: "sig", n: "...paste-public-modulus...", e: "AQAB" }] }, null, 2) };
function setStatus(message, bad = false) { e.status.textContent = message; e.status.className = bad ? "error" : ""; }
function options() { return { issuer: e.issuer.value.trim(), audience: e.audience.value.trim(), clockSkew: Number(e.skew.value) || 60 }; }
function download(name, data, type) { const url = URL.createObjectURL(new Blob([data], { type })); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function allFindings() { return [...(report?.headerFindings || []), ...(report?.claimFindings || []), ...(report?.verificationFindings || [])]; }
function render() { if (!report) return; const s = report.summary; e.errors.textContent = s.errors; e.warnings.textContent = s.warnings; e.info.textContent = s.info; e.signature.textContent = report.signatureValid === undefined ? "Not verified" : report.signatureValid ? "Valid" : "Invalid"; e.signature.className = report.signatureValid === true ? "good" : report.signatureValid === false ? "bad" : ""; e.header.textContent = JSON.stringify(report.parsed.header, null, 2); e.payload.textContent = JSON.stringify(report.parsed.payload, null, 2); e.key.textContent = report.key?.key ? JSON.stringify(report.key.key, null, 2) : "No key selected"; e.findings.replaceChildren(); allFindings().forEach((item) => { const row = document.createElement("div"); row.className = `finding ${item.severity}`; const title = document.createElement("b"); title.textContent = `${item.severity.toUpperCase()} · ${item.message}`; const detail = document.createElement("span"); detail.textContent = `${item.code}${item.detail ? ` · ${item.detail}` : ""}`; row.append(title, detail); e.findings.append(row); }); }
function inspect() { try { report = J.inspect(e.token.value, options()); setStatus("Token decoded and claims audited locally."); render(); } catch (error) { setStatus(error.message, true); } }
async function verify() { try { report = await J.verify(e.token.value, e.keys.value, options()); setStatus(report.signatureValid ? "Signature verified with the selected local JWK." : "Verification completed; inspect the findings.", !report.signatureValid); render(); } catch (error) { setStatus(error.message, true); } }
e.inspect.onclick = inspect; e.verify.onclick = verify; e.sample.onclick = () => { e.token.value = SAMPLE.token; e.keys.value = SAMPLE.keys; e.issuer.value = "https://idp.example.com"; e.audience.value = "api"; inspect(); }; e.markdown.onclick = () => { if (report) download("jwt-trust.md", J.formatMarkdown(report), "text/markdown"); }; e.json.onclick = () => { if (report) download("jwt-trust.json", JSON.stringify({ summary: report.summary, header: report.parsed.header, payload: report.parsed.payload, signatureValid: report.signatureValid, findings: allFindings() }, null, 2), "application/json"); }; e.sample.click();
