const C = window.ApiContractDiff;
const $ = (id) => document.getElementById(id);
const e = { before: $('before'), after: $('after'), compare: $('compare'), sample: $('sample'), swap: $('swap'), markdown: $('markdown'), json: $('json'), status: $('status'), report: $('report'), breaking: $('breaking'), warnings: $('warnings'), info: $('info'), operations: $('operations'), severity: $('severity'), query: $('query'), changes: $('changes'), readout: $('readout'), operationsList: $('operations-list') };
const BASE = { openapi: '3.1.0', info: { title: 'Pet API' }, paths: { '/pets/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }], get: { operationId: 'getPet', responses: { '200': { description: 'ok', content: { 'application/json': { schema: { $ref: '#/components/schemas/Pet' } } } }, '404': { description: 'missing' } } } }, '/health': { get: { operationId: 'health', responses: { '200': { description: 'ok' } } } } }, components: { schemas: { Pet: { type: 'object', required: ['id', 'name'], properties: { id: { type: 'string' }, name: { type: 'string' }, tags: { type: 'array', items: { type: 'string' } } } } } } };
function changed() { const value = JSON.parse(JSON.stringify(BASE)); value.paths['/health'].get.responses['200'].description = 'healthy'; delete value.paths['/pets/{id}'].get.responses['404']; value.components.schemas.Pet.required = ['id']; delete value.components.schemas.Pet.properties.name; value.paths['/pets/{id}'].get.parameters = [{ name: 'limit', in: 'query', required: true, schema: { type: 'integer' } }]; return value; }
function setStatus(message, bad = false) { e.status.textContent = message; e.status.className = bad ? 'error' : ''; }
function download(name, data, type) { const url = URL.createObjectURL(new Blob([data], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
let diff;
function render() { if (!diff) return; const s = diff.summary; e.report.hidden = false; e.breaking.textContent = s.breaking; e.warnings.textContent = s.warnings; e.info.textContent = s.info; e.operations.textContent = `${s.beforeOperations} -> ${s.afterOperations}`; renderChanges(); e.readout.replaceChildren(); [['Removed operations', s.removedOperations, s.removedOperations ? 'breaking' : ''], ['Added operations', s.addedOperations, ''], ['Compatibility gate', s.breaking ? 'FAIL' : 'PASS', s.breaking ? 'breaking' : 'good']].forEach(([label, value, kind]) => { const row = document.createElement('div'); row.className = 'readout ' + kind; const b = document.createElement('b'); const span = document.createElement('span'); b.textContent = label; span.textContent = value; row.append(b, span); e.readout.append(row); }); e.operationsList.replaceChildren(); diff.after.operations.forEach((operation) => { const row = document.createElement('div'); row.className = 'op'; const b = document.createElement('b'); const span = document.createElement('span'); b.textContent = operation.method; span.textContent = operation.path; row.append(b, span); e.operationsList.append(row); }); }
function renderChanges() { const changes = C.filterChanges(diff.changes, { severity: e.severity.value, query: e.query.value }); e.changes.replaceChildren(); if (!changes.length) { const empty = document.createElement('p'); empty.textContent = 'No changes match this filter.'; empty.className = 'muted'; e.changes.append(empty); return; } changes.forEach((change) => { const row = document.createElement('div'); row.className = `change ${change.severity}`; const title = document.createElement('b'); const detail = document.createElement('span'); title.textContent = `${change.severity.toUpperCase()} | ${change.message}`; detail.textContent = `${change.code} @ ${change.path}`; row.append(title, detail); e.changes.append(row); }); }
function compare() { try { diff = C.compareDocuments(e.before.value, e.after.value); setStatus(`${diff.changes.length} contract changes found.`); render(); } catch (error) { diff = null; e.report.hidden = true; setStatus(error.message, true); } }
e.compare.onclick = compare; e.sample.onclick = () => { e.before.value = JSON.stringify(BASE, null, 2); e.after.value = JSON.stringify(changed(), null, 2); compare(); }; e.swap.onclick = () => { const value = e.before.value; e.before.value = e.after.value; e.after.value = value; compare(); }; e.markdown.onclick = () => { if (diff) download('api-contract-diff.md', C.formatMarkdown(diff), 'text/markdown'); }; e.json.onclick = () => { if (diff) download('api-contract-diff.json', JSON.stringify(diff, null, 2), 'application/json'); }; [e.severity, e.query].forEach((input) => input.oninput = renderChanges); e.sample.click();
